In [231]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
import requests as re

In [232]:
url='https://www.amazon.in/New-Apple-iPhone-12-128GB/product-reviews/B08L5TNJHG/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2'

In [233]:
page=re.get(url)

In [234]:
page

In [236]:
soup1=bs(page.content,'html.parser')

In [1]:
# soup1

NameError: name 'soup1' is not defined

In [238]:
# print(soup1.prettify())

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-in">
 <!-- sp:feature:head-start -->
 <head>
  <script>
   var aPageStart = (new Date()).getTime();
  </script>
  <meta charset="utf-8"/>
  <!-- sp:end-feature:head-start -->
  <!-- sp:feature:csm:head-open-part1 -->
  <!-- sp:end-feature:csm:head-open-part1 -->
  <!-- sp:feature:cs-optimization -->
  <meta content="on" http-equiv="x-dns-prefetch-control"/>
  <link href="https://images-eu.ssl-images-amazon.com" rel="dns-prefetch"/>
  <link href="https://m.media-amazon.com" rel="dns-prefetch"/>
  <link href="https://completion.amazon.com" rel="dns-prefetch"/>
  <!-- sp:end-feature:cs-optimization -->
  <!-- sp:feature:csm:head-open-part2 -->
  <!-- sp:end-feature:csm:head-open-part2 -->
  <!-- sp:feature:aui-assets -->
  <link href="https://m.media-amazon.com/images/I/11EIQ5IGqaL._RC|01ZTHTZObnL.css,41C-I1lXVwL.css,31ufSReDtSL.css,013z33uKh2L.css,017DsKjNQJL.css,0131vqwP5UL.css,41EWOOlBJ9L.css,11TIuySqr6L.css,01ElnPiDxWL.css,11Qjwq-j69L.css,01Dm5eKVxwL.css,01IdKcBuAdL.css,01y-XAlI+2L.css,21P6CS3L9LL.css,01oDR3IULNL.css,41cg-OrH1jL.css,01XPHJk60-L.css,01smHc51S9L.css,21aPhFy+riL.css,11gneA3MtJL.css,21fecG8pUzL.css,11a5wZbuKrL.css,01CFUgsA-YL.css,31C80IiXalL.css,11qour3ND0L.css,11gKCCKQV+L.css,11061HxnEvL.css,11oHt2HYxnL.css,01uPgw4sNAL.css,11JQtnL-6eL.css,116v6uYvN6L.css,11jtXRmppwL.css,01QrWuRrZ-L.css,21uwtfqr5aL.css,11QyqG8yiqL.css,11K24eOJg4L.css,11F2+OBzLyL.css,01890+Vwk8L.css,11Y05DTEL6L.css,01cbS3UK11L.css,21F85am0yFL.css,01giMEP+djL.css_.css?AUIClients/AmazonUI&amp;5bV+ZZS7#not-trident.388250-T1.417812-T1.417828-T1" rel="stylesheet">
   <script>
    (function(d,f,R,H){function w(a){z&&z.tag&&z.tag(l(":","aui",a))}function n(a,b){z&&z.count&&z.count("aui:"+a,0===b?0:b||(z.count("aui:"+a)||0)+1)}function t(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function u(a){return"function"===typeof a}function C(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function l(a,b,c,d){b=b&&c?b+a+c:b||c;return d?l(a,b,d):b}function I(a,b,c){try{Object.defineProperty(a,b,{value:c,writable:!1})}catch(x){a[b]=
c}return c}function ta(a,b,c){var d=c=a.length,g=function(){d--||(S.push(b),T||(setTimeout(da,0),T=!0))};for(g();c--;)ea[a[c]]?g():(y[a[c]]=y[a[c]]||[]).push(g)}function ua(a,b,c,d,g){var e=f.createElement(a?"script":"link");C(e,"error",d);g&&C(e,"load",g);a?(e.type="text/javascript",e.async=!0,c&&/AUIClients|images[/]I/.test(b)&&e.setAttribute("crossorigin","anonymous"),e.src=b):(e.rel="stylesheet",e.href=b);f.getElementsByTagName("head")[0].appendChild(e)}function fa(a,b){return function(c,x){function g(){ua(b,
c,e,function(b){U?n("resource_unload"):e?(e=!1,n("resource_retry"),g()):(n("resource_error"),a.log("Asset failed to load: "+c));b&&b.stopPropagation?b.stopPropagation():d.event&&(d.event.cancelBubble=!0)},x)}if(ha[c])return!1;ha[c]=!0;n("resource_count");var e=!0;return!g()}}function va(a,b,c){for(var d={name:a,guard:function(c){return b.guardFatal(a,c)},guardTime:function(a){return b.guardTime(a)},logError:function(c,d,e){b.logError(c,d,e,a)}},g=[],e=0;e<c.length;e++)J.hasOwnProperty(c[e])&&(g[e]=
V.hasOwnProperty(c[e])?V[c[e]](J[c[e]],d):J[c[e]]);return g}function D(a,b,c,x,g){return function(e,f){function n(){var a=null;x?a=f:u(f)&&(m.start=B(),a=f.apply(d,va(e,h,p)),m.end=B());if(b){J[e]=a;a=e;for(ea[a]=!0;(y[a]||[]).length;)y[a].shift()();delete y[a]}m.done=!0}var h=g||this;u(e)&&(f=e,e=H);b&&(e=e?e.replace(ia,""):"__NONAME__",W.hasOwnProperty(e)&&h.error(l(", reregistered by ",l(" by ",e+" already registered",W[e]),h.attribution),e),W[e]=h.attribution);for(var p=[],k=0;k<a.length;k++)p[k]=
a[k].replace(ia,"");var m=E[e||"anon"+ ++wa]={depend:p,registered:B(),namespace:h.namespace};e&&xa.hasOwnProperty(e);c?n():ta(p,h.guardFatal(e,n),e);return{decorate:function(a){V[e]=h.guardFatal(e,a)}}}}function ja(a){return function(){var b=Array.prototype.slice.call(arguments);return{execute:D(b,!1,a,!1,this),register:D(b,!0,a,!1,this)}}}function X(a,b){return function(c,d){d||(d=c,c=H);var g=this.attribution;return function(){q.push(b||{attribution:g,name:c,logLevel:a});var e=d.apply(this,arguments);
q.pop();return e}}}function K(a,b){this.load={js:fa(this,!0),css:fa(this)};I(this,"namespace",b);I(this,"attribution",a)}function ka(){f.body?v.trigger("a-bodyBegin"):setTimeout(ka,20)}function F(a,b){a.className=Y(a,b)+" "+b}function Y(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function la(a){try{return a()}catch(b){return!1}}function L(){if(M){var a={w:d.innerWidth||h.clientWidth,h:d.innerHeight||h.clientHeight};5<Math.abs(a.w-Z.w)||50<a.h-Z.h?(Z=a,N=4,(a=k.mobile||
k.tablet?450<a.w&&a.w>a.h:1250<=a.w)?F(h,"a-ws"):h.className=Y(h,"a-ws")):0<N&&(N--,ma=setTimeout(L,16))}}function ya(a){(M=a===H?!M:!!a)&&L()}function za(){return M}"use strict";var O=R.now=R.now||function(){return+new R},B=function(a){return a&&a.now?a.now.bind(a):O}(d.performance),P=B(),xa={},r=d.AmazonUIPageJS||d.P;if(r&&r.when&&r.register){P=[];for(var m=f.currentScript;m;m=m.parentElement)m.id&&P.push(m.id);return r.log("A copy of P has already been loaded on this page.","FATAL",P.join(" "))}var z=
d.ue;w();w("aui_build_date:3.22.2-2022-12-22");var S=[],Aa=[],T=!1;var da=function(){for(var a=setTimeout(da,0),b=O();Aa.length||S.length;)if(S.shift()(),50<O()-b)return;clearTimeout(a);T=!1};var ea={},y={},ha={},U=!1;C(d,"beforeunload",function(){U=!0;setTimeout(function(){U=!1},1E4)});var ia=/^prv:/,W={},J={},V={},E={},wa=0,aa=String.fromCharCode(92),q=[],na=!0,oa=d.onerror;d.onerror=function(a,b,c,x,g){g&&"object"===typeof g||(g=Error(a,b,c),g.columnNumber=x,g.stack=b||c||x?l(aa,g.message,"at "+
l(":",b,c,x)):H);var e=q.pop()||{};g.attribution=l(":",g.attribution||e.attribution,e.name);g.logLevel=e.logLevel;g.attribution&&console&&console.log&&console.log([g.logLevel||"ERROR",a,"thrown by",g.attribution].join(" "));q=[];oa&&(e=[].slice.call(arguments),e[4]=g,oa.apply(d,e))};K.prototype={logError:function(a,b,c,x){b={message:b,logLevel:c||"ERROR",attribution:l(":",this.attribution,x)};if(d.ueLogError)return d.ueLogError(a||b,a?b:null),!0;console&&console.error&&(console.log(b),console.error(a));
return!1},error:function(a,b,c,d){a=Error(l(":",d,a,c));a.attribution=l(":",this.attribution,b);throw a;},guardError:X(),guardFatal:X("FATAL"),guardCurrent:function(a){var b=q[q.length-1];return b?X(b.logLevel,b).call(this,a):a},guardTime:function(a){var b=q[q.length-1],c=b&&b.name;return c&&c in E?function(){var b=B(),d=a.apply(this,arguments);E[c].async=(E[c].async||0)+B()-b;return d}:a},log:function(a,b,c){return this.logError(null,a,b,c)},declare:D([],!0,!0,!0),register:D([],!0),execute:D([]),
AUI_BUILD_DATE:"3.22.2-2022-12-22",when:ja(),now:ja(!0),trigger:function(a,b,c){var f=O();this.declare(a,{data:b,pageElapsedTime:f-(d.aPageStart||NaN),triggerTime:f});c&&c.instrument&&G.when("prv:a-logTrigger").execute(function(b){b(a)})},handleTriggers:function(){this.log("handleTriggers deprecated")},attributeErrors:function(a){return new K(a)},_namespace:function(a,b){return new K(a,b)},setPriority:function(a){na?na=!1:this.log("setPriority only accept the first call.")}};var v=I(d,"AmazonUIPageJS",
new K);var G=v._namespace("PageJS","AmazonUI");G.declare("prv:p-debug",E);v.declare("p-recorder-events",[]);v.declare("p-recorder-stop",function(){});I(d,"P",v);ka();if(f.addEventListener){var pa;f.addEventListener("DOMContentLoaded",pa=function(){v.trigger("a-domready");f.removeEventListener("DOMContentLoaded",pa,!1)},!1)}var h=f.documentElement,ba=function(){var a=["O","ms","Moz","Webkit"],b=f.createElement("div");return{testGradients:function(){return!0},test:function(c){var d=c.charAt(0).toUpperCase()+
c.substr(1);c=(a.join(d+" ")+d+" "+c).split(" ");for(d=c.length;d--;)if(""===b.style[c[d]])return!0;return!1},testTransform3d:function(){return!0}}}();r=h.className;var qa=/(^| )a-mobile( |$)/.test(r),ra=/(^| )a-tablet( |$)/.test(r),k={audio:function(){return!!f.createElement("audio").canPlayType},video:function(){return!!f.createElement("video").canPlayType},canvas:function(){return!!f.createElement("canvas").getContext},svg:function(){return!!f.createElementNS&&!!f.createElementNS("http://www.w3.org/2000/svg",
"svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in f.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!d.history||!d.history.pushState)},webworker:function(){return!!d.Worker},autofocus:function(){return"autofocus"in f.createElement("input")},inputPlaceholder:function(){return"placeholder"in f.createElement("input")},textareaPlaceholder:function(){return"placeholder"in
f.createElement("textarea")},localStorage:function(){return"localStorage"in d&&null!==d.localStorage},orientation:function(){return"orientation"in d},touch:function(){return"ontouchend"in f},gradients:function(){return ba.testGradients()},hires:function(){var a=d.devicePixelRatio&&1.5<=d.devicePixelRatio||d.matchMedia&&d.matchMedia("(min-resolution:144dpi)").matches;n("hiRes"+(qa?"Mobile":ra?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return ba.testTransform3d()},touchScrolling:function(){return t(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},
ios:function(){return t(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!t(/trident|Edge/i)},android:function(){return t(/android.([1-9]|[L-Z])/i)&&!t(/trident|Edge/i)},mobile:function(){return qa},tablet:function(){return ra},rtl:function(){return"rtl"===h.dir}};for(m in k)k.hasOwnProperty(m)&&(k[m]=la(k[m]));for(var ca="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),Q=0;Q<ca.length;Q++)k[ca[Q]]=la(function(){return ba.test(ca[Q])});var M=!0,ma=0,Z=
{w:0,h:0},N=4;L();C(d,"resize",function(){clearTimeout(ma);N=4;L()});var sa={getItem:function(a){try{return d.localStorage.getItem(a)}catch(b){}},setItem:function(a,b){try{return d.localStorage.setItem(a,b)}catch(c){}}};h.className=Y(h,"a-no-js");F(h,"a-js");!t(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||d.navigator.standalone||t(/safari/i)||F(h,"a-ember");r=[];for(m in k)k.hasOwnProperty(m)&&k[m]&&r.push("a-"+m.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));F(h,r.join(" "));h.setAttribute("data-aui-build-date",
"3.22.2-2022-12-22");v.register("p-detect",function(){return{capabilities:k,localStorage:k.localStorage&&sa,toggleResponsiveGrid:ya,responsiveGridEnabled:za}});t(/UCBrowser/i)||k.localStorage&&F(h,sa.getItem("a-font-class"));v.declare("a-event-revised-handling",!1);v.execute("RetailPageServiceWorker",function(){function a(a,b){p.controller&&a?(a={feature:"retail_service_worker_messaging",command:a},b&&(a.data=b),p.controller.postMessage(a)):a&&n("sw:sw_message_no_ctrl",1)}function b(a){var b=a.data;
if(b&&"retail_service_worker_messaging"===b.feature&&b.command&&b.data){var c=b.data;a=d.ue;var e=d.ueLogError;switch(b.command){case "log_counter":a&&u(a.count)&&c.name&&a.count(c.name,0===c.value?0:c.value||1);break;case "log_tag":a&&u(a.tag)&&c.tag&&(a.tag(c.tag),b=d.uex,a.isl&&u(b)&&b("at"));break;case "log_error":e&&u(e)&&c.message&&e({message:c.message,logLevel:c.level||"ERROR",attribution:c.attribution||"RetailServiceWorker"});break;case "log_weblab_trigger":a&&u(a.trigger)&&c.weblab&&c.treatment&&
a.trigger(c.weblab,c.treatment);break;default:n("sw:unsupported_message_command",1)}}}function c(a,b){return"sw:"+(b||"")+":"+a+":"}function h(a,b){try{p.getRegistrations().then(function(c){c.forEach(function(c){c.unregister().then(function(){n(a+"success")}).catch(function(c){g(c,a,b)})})})}catch(Ca){w("sw:api_error")}}function g(a,b,c){v.logError(a,"[AUI SW] Failed to "+c+" service worker: ","ERROR","RetailPageServiceWorker");n(b+"failure")}function e(){q.forEach(function(a){w(a)})}function k(a){return a.capabilities.isAmazonApp&&
a.capabilities.android}function m(a,b,d){if(b)if(b.mshop&&k(a))a=c(d,"mshop_and"),b=b.mshop.action,q.push(a+"supported"),b(a,d);else if(b.browser){a=t(/Chrome/i)&&!t(/Edge/i)&&!t(/OPR/i)&&!a.capabilities.isAmazonApp&&!t(new RegExp(aa+"bwv"+aa+"b"));var e=b.browser;b=c(d,"browser");a?(a=e.action,q.push(b+"supported"),a(b,d)):q.push(b+"unsupported")}}function r(a,b,d){a&&q.push(c("register",d)+"unsupported");b&&q.push(c("unregister",d)+"unsupported");e()}try{var p=navigator.serviceWorker}catch(Ba){w("sw:nav_err")}(function(){if(p){var c=
function(){a("page_loaded",{rid:d.ue_id,mid:d.ue_mid,pty:d.ue_pty,sid:d.ue_sid,spty:d.ue_spty,furl:d.ue_furl})};C(p,"message",b);a("client_messaging_ready");v.when("load").execute(c);C(p,"controllerchange",function(){a("client_messaging_ready");"complete"===f.readyState&&c()})}})();var q=[],A=function(a,b){var c=d.uex,e=d.uet;a=l(":","aui","sw",a);"ld"===b&&u(c)?c("ld",a,{wb:1}):u(e)&&e(b,a,{wb:1})},B=function(a,b,c){function e(a){b&&u(b.failure)&&b.failure(a)}function g(){k=setTimeout(function(){w(l(":",
"sw:"+h,f.TIMED_OUT));e({ok:!1,statusCode:f.TIMED_OUT,done:!1});A(h,"ld")},c||4E3)}var f={NO_CONTROLLER:"no_ctrl",TIMED_OUT:"timed_out",UNSUPPORTED_BROWSER:"unsupported_browser",UNEXPECTED_RESPONSE:"unexpected_response"},h=l(":",a.feature,a.command),k,m=!0;if("MessageChannel"in d&&p&&"controller"in p)if(p.controller){var q=new MessageChannel;q.port1.onmessage=function(c){(c=c.data)&&c.feature===a.feature&&c.command===a.command?(m&&(A(h,"cf"),m=!1),A(h,"af"),clearTimeout(k),c.done||g(),c.ok?b&&u(b.success)&&
b.success(c):e(c),c.done&&A(h,"ld")):n(l(":","sw:"+h,f.UNEXPECTED_RESPONSE),1)};g();A(h,"bb");p.controller.postMessage(a,[q.port2])}else w(l(":","sw:"+a.feature,f.NO_CONTROLLER)),e({ok:!1,statusCode:f.NO_CONTROLLER,done:!0});else w(l(":","sw:"+a.feature,f.UNSUPPORTED_BROWSER)),e({ok:!1,statusCode:f.UNSUPPORTED_BROWSER,done:!0})};(function(){p?(A("ctrl_changed","bb"),p.addEventListener("controllerchange",function(){w("sw:ctrl_changed");A("ctrl_changed","ld")})):n(l(":","sw:ctrl_changed","sw_unsupp"),
1)})();(function(){var a=function(){A(b,"ld");var a=d.uex;B({feature:"page_proxy",command:"request_feature_tags"},{success:function(b){b=b.data;Array.isArray(b)&&b.forEach(function(a){"string"===typeof a?w(l(":","sw:ppft",a)):n(l(":","sw:ppft","invalid_tag"),1)});n(l(":","sw:ppft","success"),1);z&&z.isl&&u(a)&&a("at")},failure:function(a){n(l(":","sw:ppft","error:"+(a.statusCode||"ppft_error")),1)}})};if("requestIdleCallback"in d){var b=l(":","ppft","callback_ricb");d.requestIdleCallback(a,{timeout:1E3})}else b=
l(":","ppft","callback_timeout"),setTimeout(a,0);A(b,"bb")})();var y={reg:{},unreg:{}};y.unreg.mshopBeta={action:h};y.unreg.mshop={action:h};y.reg.browser={action:function(a,b){p.register("/service-worker.js").then(function(){n(a+"success")}).catch(function(c){g(c,a,b)})}};(function(a){var b=a.reg,c=a.unreg;p&&p.getRegistrations?(G.when("A").execute(function(b){if((a.reg.mshop||a.unreg.mshop)&&"function"===typeof k&&k(b)){var e=a.reg.mshop?"T1":"C",f=d.ue;f&&f.trigger?f.trigger("MSHOP_SW_CLIENT_446196",
e):n("sw:mshop:wt:failed")}m(b,c,"unregister")}),C(d,"load",function(){G.when("A").execute(function(a){m(a,b,"register");e()})})):(r(b&&b.browser,c&&c.browser,"browser"),G.when("A").execute(function(a){"function"===typeof k&&k(a)&&r(b&&b.mshop,c&&c.mshop,"mshop_and")}))})(y)});v.declare("a-fix-event-off",!1);n("pagejs:pkgExecTime",B()-P)})(window,document,Date);
(function(b){function q(a,e,d){function g(a,b,c){var f=Array(e.length);~l&&(f[l]={});~m&&(f[m]=c);for(c=0;c<n.length;c++){var g=n[c],h=a[c];f[g]=h}for(c=0;c<p.length;c++)g=p[c],h=b[c],f[g]=h;a=d.apply(null,f);return~l?f[l]:a}"string"!==typeof a&&b.P.error("C001");-1===a.indexOf("@")&&-1<a.indexOf("/")&&(-1<a.indexOf("es3")||-1<a.indexOf("evergreen"))&&(a=a.substring(0,a.lastIndexOf("/")));if(!r[a]){r[a]=!0;d||(d=e,e=[]);a=a.split(":",2);var c=a[1]?a[0]:void 0,f=(a[1]||a[0]).replace(/@capability\//,
"@c/"),k=c?b.P._namespace(c):b.P,t=!f.lastIndexOf("@c/",0),u=!f.lastIndexOf("@m/",0),n=[];a=[];var p=[],v=[],m=-1,l=-1;for(c=0;c<e.length;c++){var h=e[c];"module"===h&&k.error("C002");"exports"===h?l=c:"require"===h?m=c:h.lastIndexOf("@p/",0)?h.lastIndexOf("@c/",0)&&h.lastIndexOf("@m/",0)?(n.push(c),a.push("mix:"+h)):(p.push(c),v.push(h)):(n.push(c),a.push(h.substr(3)))}k.when.apply(k,a).register("mix:"+f,function(){var a=[].slice.call(arguments);return t||u||~m||p.length?{capabilities:v,cardModuleFactory:function(b,
c){b=g(a,b,c);b.P=k;return b},require:~m?q:void 0}:g(a,[],function(){})});(t||u)&&k.when("mix:@amzn/mix.client-runtime","mix:"+f).execute(function(a,b){a.registerCapabilityModule(f,b)});k.when("mix:"+f).register("xcp:"+f,function(a){return a});var q=function(a,b,c){try{var e=-1<f.indexOf("/")?f.split("/")[0]:f,d=a[0],g=d.lastIndexOf("./",0)?d:e+"/"+d.substr(2),h=g.lastIndexOf("@p/",0)?"mix:"+g:g.substr(3);k.when(h).execute(function(a){try{b(a)}catch(x){c(x)}})}catch(w){c(w)}}}}"use strict";var r=
{};b.mix_d||((b.Promise?P:P.when("3p-promise")).register("@p/promise-is-ready",function(a){b.Promise=b.Promise||a}),(Array.prototype.includes?P:P.when("a-polyfill")).register("@p/polyfill-is-ready",function(){}),b.mix_d=function(a,b,d){P.when("@p/promise-is-ready","@p/polyfill-is-ready").execute("@p/mix-d-deps",function(){q(a,b,d)})},b.xcp_d=b.mix_d,P.when("mix:@amzn/mix.client-runtime").execute(function(a){P.declare("xcp:@xcp/runtime",a)}));b.mixTimeout||(b.mixTimeout=function(a,e,d){b.mixCardInitTimeouts||
(b.mixCardInitTimeouts={});b.mixCardInitTimeouts[e]&&clearTimeout(b.mixCardInitTimeouts[e]);b.mixCardInitTimeouts[e]=setTimeout(function(){P.log("Client-side initialization timeout","WARN",a)},d)});b.mix_csa_map=b.mix_csa_map||{};b.mix_csa_internal=b.mix_csa_internal||function(a,e,d){return b.mix_csa_map[e]=b.mix_csa_map[e]||b.csa(a,d)};b.mix_csa_internal_key=b.mix_csa_internal_key||function(a,b){for(var d="",e=0;e<b.length;e++){var c=b[e];void 0!==a[c]&&"object"!==typeof a[c]&&(d+=c+":"+a[c]+",")}if(!d)throw Error("bad mix-csa key gen.");
return d};b.mix_csa_event=b.mix_csa_event||function(a){try{var e=b.mix_csa_internal_key(a,["producerId"])}catch(d){return P.logError(d,"MIX C005","WARN",void 0),function(){}}try{return b.mix_csa_internal("Events",e,a)}catch(d){return P.logError(d,"MIX C004","WARN",e),function(){}}};b.mix_csa=b.mix_csa||function(a,e){try{e=e||"";var d=document.querySelectorAll(a);if(1<d.length)for(var g=0;g<d.length;g++){if(d[g].querySelector(e)){var c=d[g];break}}else 1===d.length&&(c=d[0]);if(!c)throw Error(" ");
return b.mix_csa_internal("Content",a,{element:c})}catch(f){return P.logError(f,"MIX C004","WARN",a),function(){}}}})(window);
(window.AmazonUIPageJS ? AmazonUIPageJS : P).when('sp.load.js').execute(function() {
  (window.AmazonUIPageJS ? AmazonUIPageJS : P).load.js('https://m.media-amazon.com/images/I/61NeHXhGwSL.js?AUIClients/AmazonUIjQuery&KK9dlo3A#412402-T1.412405-T1');
  (window.AmazonUIPageJS ? AmazonUIPageJS : P).load.js('https://m.media-amazon.com/images/I/11Y+5x+kkTL._RC|51fH61+ExwL.js,11yKORv-GTL.js,11giXtZCwVL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21SDJtBU-PL.js,012FVc3131L.js,11rRjDLdAVL.js,516j7qaWchL.js,11kWu3cNjYL.js,11aKqyRXooL.js,11OREnu1epL.js,11qVTZscrRL.js,21ssiLNIZvL.js,0190vxtlzcL.js,51+N26vFcBL.js,01JYHc2oIlL.js,31nfKXylf6L.js,01ezj5Rkz1L.js,11bEz2VIYrL.js,31o2NGTXThL.js,01rpauTep4L.js,01wGRCg6A5L.js_.js?AUIClients/AmazonUI');
  (window.AmazonUIPageJS ? AmazonUIPageJS : P).load.js('https://m.media-amazon.com/images/I/51SrwqaWgEL.js?AUIClients/CardJsRuntimeBuzzCopyBuild');
});
   </script>
   <!-- sp:end-feature:aui-assets -->
   <!-- sp:feature:nav-inline-css -->
   <!-- NAVYAAN CSS -->
   <style type="text/css">
    .nav-sprite-v1 .nav-sprite, .nav-sprite-v1 .nav-icon {
  background-image: url(https://m.media-amazon.com/images/G/31/gno/sprites/nav-sprite-global-1x-hm-dsk-reorg._CB405936311_.png);

In [239]:
names1=soup1.find_all('div',class_='a-profile-content')

In [240]:
cust_name1=[]
for i in range(0,len(names1)):
    cust_name1.append(names1[i].get_text())

In [241]:
cust_name1

['Abhishek',
 'Yaswanth S.',
 'Sandip Bangar',
 'Nazimulla Alam Khan',
 'Hozefa',
 'Jaskarn singh',
 'Kashyap',
 'KAMRAN AMIN',
 'Bhupendra Meghwal',
 'Suhas G.',
 'Placeholder',
 'Anil j.']

In [242]:
cust_name1.pop(0)

'Abhishek'

In [243]:
cust_name1.pop(0)

'Yaswanth S.'

In [244]:
review_title1=soup1.find_all('a',class_='review-title')

In [245]:
review_title1

[<a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R176VVNZHPUTLQ?ASIN=B08L5TNJHG">
 <span>Good</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R1WEKKX7B761RO?ASIN=B08L5TNJHG">
 <span>Iphone 12</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R2L3QW06O7R06I?ASIN=B08L5TNJHG">
 <span>It’s iPhone simply the best</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/RJ8JQ3CZDTHRZ?ASIN=B08L5TNJHG">
 <span>Best</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R3V9CS23X1XNYU?ASIN=B08L5TNJHG">
 <span>Best mobile best price under 52k/128gb</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R1U0Q1586G5UV?ASIN=B08L5TNJHG">
 <span>Good phone</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R1IFEEE9OUSHBX?ASIN=B08L5TNJHG">
 <span>As expected</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/RHPZ0ZP2N9CIH?ASIN=B08L5TNJHG">
 <span>Good for normal use</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R1KVY4K4N8WYB4?ASIN=B08L5TNJHG">
 <span>Premium phone with poor battery and average camera</span>
 </a>,
 <a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R12D2QH04QCT8X?ASIN=B08L5TNJHG">
 <span>Deffect</span>
 </a>]

In [246]:
re_title1=[]
for i in range(0,len(review_title1)):
    re_title1.append(review_title1[i].get_text())
re_title1

['\nGood\n',
 '\nIphone 12\n',
 '\nIt’s iPhone simply the best\n',
 '\nBest\n',
 '\nBest mobile best price under 52k/128gb\n',
 '\nGood phone\n',
 '\nAs expected\n',
 '\nGood for normal use\n',
 '\nPremium phone with poor battery and average camera\n',
 '\nDeffect\n']

In [247]:
#list comprehension
re_title1[:]=[titles.lstrip('\n') for titles in re_title1]

In [248]:
re_title1

['Good\n',
 'Iphone 12\n',
 'It’s iPhone simply the best\n',
 'Best\n',
 'Best mobile best price under 52k/128gb\n',
 'Good phone\n',
 'As expected\n',
 'Good for normal use\n',
 'Premium phone with poor battery and average camera\n',
 'Deffect\n']

In [249]:
re_title1[:]=[titles.rstrip() for titles in re_title1]

In [250]:
re_title1

['Good',
 'Iphone 12',
 'It’s iPhone simply the best',
 'Best',
 'Best mobile best price under 52k/128gb',
 'Good phone',
 'As expected',
 'Good for normal use',
 'Premium phone with poor battery and average camera',
 'Deffect']

In [251]:
rating1=soup1.find_all('i',class_='review-rating')

In [252]:
rating1

[<i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating-view-point"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-3 review-rating" data-hook="review-star-rating-view-point"><span class="a-icon-alt">3.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i>,
 <i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i>]

In [253]:
ratings1=[]
for i in range(0,len(rating1)):
    ratings1.append(rating1[i].get_text())
ratings1

['4.0 out of 5 stars',
 '3.0 out of 5 stars',
 '4.0 out of 5 stars',
 '4.0 out of 5 stars',
 '5.0 out of 5 stars',
 '4.0 out of 5 stars',
 '5.0 out of 5 stars',
 '4.0 out of 5 stars',
 '4.0 out of 5 stars',
 '4.0 out of 5 stars',
 '5.0 out of 5 stars',
 '4.0 out of 5 stars']

In [254]:
ratings1.pop(0)

'4.0 out of 5 stars'

In [255]:
ratings1.pop(0)

'3.0 out of 5 stars'

In [256]:
ratings1[:]=[x.rstrip(' out of 5 stars') for x in ratings1]
ratings1

['4.0', '4.0', '5.0', '4.0', '5.0', '4.0', '4.0', '4.0', '5.0', '4.0']

In [257]:
comment1=soup1.find_all('span',{'data-hook':"review-body"})
comment1

[<span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Good battery life</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Excellent phone. Battery back up is very good and fabulous camera. Excellent Sound quality. Very handy and less weighted phone.</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Am user of iPhone since last 8 yrs so no regrets on upgrading to this one. Video is far excellent and build quality is superb. Have an android phone and don’t feel like using it</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Very good</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Awesome mobile<br>Premium best camera<br/>Best performance<br/>Better battery 🔋 life<br/>Best battery optimisation and background process<br/>Vale for money and fabulous update via apple<br/>No one ecosystem , power full phone, all in one mobile,great function and features.<br/>Cone<br/>Battery must be 4000 mah<br/>Call recording not possible<br/>Not use 64 gb variants<br/>Accessories costly</br></span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Camera is good nd colour also good</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Hearing loss when talking on the phone.</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Build quality and performance is premium.<br/>iOS has its pros n cons. Recent iOS versions are less restrictive.<br/>Camera is consistent.<br/>Battery life is above average. It gets warm sometimes. Charging speed is fine. I wont recommend it for gaming.<br/>iPhones are on the pricier side but I am expecting long term use with the same snappier feel and less bugs.</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>I have upgraded from four years old iPhone 7.<br/>Only noticeable change is screen size and face unlocking.<br/>Camera doesn’t adjust exposure properly and I must say not much better from iPhone7.<br/>Let’s bear this for next 4-5 years 😊</span>
 </span>,
 <span class="a-size-base review-text review-text-content" data-hook="review-body">
 <span>Got a little bit of deffect in camera bump but its hardly noticeable</span>
 </span>]

In [258]:
re_comments1=[]
for i in range(0,len(comment1)):
    re_comments1.append(comment1[i].get_text())
re_comments1

['\nGood battery life\n',
 '\nExcellent phone. Battery back up is very good and fabulous camera. Excellent Sound quality. Very handy and less weighted phone.\n',
 '\nAm user of iPhone since last 8 yrs so no regrets on upgrading to this one. Video is far excellent and build quality is superb. Have an android phone and don’t feel like using it\n',
 '\nVery good\n',
 '\nAwesome mobilePremium best cameraBest performanceBetter battery 🔋 lifeBest battery optimisation and background processVale for money and fabulous update via appleNo one ecosystem , power full phone, all in one mobile,great function and features.ConeBattery must be 4000 mahCall recording not possibleNot use 64 gb variantsAccessories costly\n',
 '\nCamera is good nd colour also good\n',
 '\nHearing loss when talking on the phone.\n',
 '\nBuild quality and performance is premium.iOS has its pros n cons. Recent iOS versions are less restrictive.Camera is consistent.Battery life is above average. It gets warm sometimes. Charging speed is fine. I wont recommend it for gaming.iPhones are on the pricier side but I am expecting long term use with the same snappier feel and less bugs.\n',
 '\nI have upgraded from four years old iPhone 7.Only noticeable change is screen size and face unlocking.Camera doesn’t adjust exposure properly and I must say not much better from iPhone7.Let’s bear this for next 4-5 years 😊\n',
 '\nGot a little bit of deffect in camera bump but its hardly noticeable\n']

In [259]:
re_comments1[:]=[x.lstrip('\n') for x in re_comments1]

In [260]:
re_comments1[:]=[x.rstrip('\n') for x in re_comments1]

In [261]:
re_comments1

['Good battery life',
 'Excellent phone. Battery back up is very good and fabulous camera. Excellent Sound quality. Very handy and less weighted phone.',
 'Am user of iPhone since last 8 yrs so no regrets on upgrading to this one. Video is far excellent and build quality is superb. Have an android phone and don’t feel like using it',
 'Very good',
 'Awesome mobilePremium best cameraBest performanceBetter battery 🔋 lifeBest battery optimisation and background processVale for money and fabulous update via appleNo one ecosystem , power full phone, all in one mobile,great function and features.ConeBattery must be 4000 mahCall recording not possibleNot use 64 gb variantsAccessories costly',
 'Camera is good nd colour also good',
 'Hearing loss when talking on the phone.',
 'Build quality and performance is premium.iOS has its pros n cons. Recent iOS versions are less restrictive.Camera is consistent.Battery life is above average. It gets warm sometimes. Charging speed is fine. I wont recommend it for gaming.iPhones are on the pricier side but I am expecting long term use with the same snappier feel and less bugs.',
 'I have upgraded from four years old iPhone 7.Only noticeable change is screen size and face unlocking.Camera doesn’t adjust exposure properly and I must say not much better from iPhone7.Let’s bear this for next 4-5 years 😊',
 'Got a little bit of deffect in camera bump but its hardly noticeable']

In [262]:
len(re_comments1)

10

In [264]:
cust_name1
re_comments1
ratings1
re_title1

['Good',
 'Iphone 12',
 'It’s iPhone simply the best',
 'Best',
 'Best mobile best price under 52k/128gb',
 'Good phone',
 'As expected',
 'Good for normal use',
 'Premium phone with poor battery and average camera',
 'Deffect']

In [265]:
data1=pd.DataFrame({'name':cust_name1,'titles':re_title1,'rating':ratings1,'comments':re_comments1})
data1

,name,titles,rating,comments
0,Sandip Bangar,Good,4.0,Good battery life
1,Nazimulla Alam Khan,Iphone 12,4.0,Excellent phone. Battery back up is very good ...
2,Hozefa,It’s iPhone simply the best,5.0,Am user of iPhone since last 8 yrs so no regre...
3,Jaskarn singh,Best,4.0,Very good
4,Kashyap,Best mobile best price under 52k/128gb,5.0,Awesome mobilePremium best cameraBest performa...
5,KAMRAN AMIN,Good phone,4.0,Camera is good nd colour also good
6,Bhupendra Meghwal,As expected,4.0,Hearing loss when talking on the phone.
7,Suhas G.,Good for normal use,4.0,Build quality and performance is premium.iOS h...
8,Placeholder,Premium phone with poor battery and average ca...,5.0,I have upgraded from four years old iPhone 7.O...
9,Anil j.,Deffect,4.0,Got a little bit of deffect in camera bump but...

### Now i going to use for loop coz manualy i only get more than 10 user data. so using i can get user data from other pages

In [266]:
# firstly i stored urls of next pages and stored in variable
URL=[]
for i in range(1,1200):
    url='https://www.amazon.in/New-Apple-iPhone-12-128GB/product-reviews/B08L5TNJHG/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber='
    URL.append(url+str(i))

# then i exctracted name,title,rating and comments from all those pages
cust_name=[]
re_title=[]
ratings=[]
re_comments=[]

for i in URL:    
    page=re.get(i)
    
    soup=bs(page.content,'html.parser')
    
    names=soup.find_all('div',class_='a-profile-content')
    
    for i in range(0,len(names)):
        cust_name.append(names[i].get_text())
    
    review_title=soup.find_all('a',class_='review-title')
    
    for i in range(0,len(review_title)):
        re_title.append(review_title[i].get_text())

    #list comprehension to remove '\n' unwanted charactar
    re_title[:]=[titles.lstrip('\n') for titles in re_title]
    re_title[:]=[titles.rstrip('\n') for titles in re_title]
    
    rating=soup.find_all('i',class_='review-rating')
    
    for i in range(0,len(rating)):
        ratings.append(rating[i].get_text())
    ratings
    
    ratings[:]=[x.rstrip(' out of 5 stars') for x in ratings]
    ratings
    
    comment=soup.find_all('span',{'data-hook':"review-body"})
    comment
    
    for i in range(0,len(comment)):
        re_comments.append(comment[i].get_text())
    re_comments
    
    re_comments[:]=[x.lstrip('\n') for x in re_comments]
    re_comments[:]=[x.rstrip('\n') for x in re_comments]

In [267]:
if len(re_comments)<len(ratings):
    c=len(ratings)-len(re_comments)
    c=int(c)
    for i in range(0,c):
        ratings.pop(i)
        cust_name.pop(i)
        if len(re_comments)==len(ratings):
            print('now the length is equal of both variables')

now the length is equal of both variables

In [268]:
len(re_comments)

2035

In [269]:
len(ratings)

2035

In [270]:
len(re_title)

2035

In [271]:
# i tried to convert into dataframe but some of the values from colunms was missing so i cant create the dataframe
#data=pd.DataFrame({'name':cust_name,'rating':ratings,'titles':re_title,'comments':re_comments,})

In [272]:
data=pd.DataFrame({'name':cust_name,'titles':re_title,'rating':ratings,'comments':re_comments})
data

,name,titles,rating,comments
0,Yaswanth S.,An overall good premium experience,3.0,"SUMMERY: As a first time iPhone user, I would ..."
1,Navish Paik,Excellent product,4.0,Satisfied with the quality and performance but...
2,Mantu kumar,In the era of 14 this is still beast,4.0,"Using for few months, no heating issue, but ni..."
3,Yogesh Kumar Sharma,mujhe acha laga istmal kar ke,4.0,In 2022 best iPhone ever
4,Swapnil S Joshi,iphone 12 is good for normal use but don’t exp...,4.0,"Whereas brand is apple, you can expect standar..."
...,...,...,...,...
2030,Yaswanth S.,Better than ever.. Real premium product,3.0,Upgraded from 7+. Amazing product. Loving it.
2031,Abhishek,Really awesome,4.0,No need to comment because this is Apple.
2032,Yaswanth S.,It’s just an update nothing special,3.0,Upgraded from iPhone x after over 3 years. I d...
2033,Abhishek,100 original iphone no fake,4.0,"Just great, feel awesome to unbox all good at ..."
2034,Yaswanth S.,Valur for money,3.0,Good performance

In [273]:
data.to_csv(r'Iphone-12_Review.csv',index=True)

###  Now we are doing emotion mining on the dataset

In [274]:
# we imported saved csv file so we can check is it having any issue while importing or not
data=pd.read_csv('Iphone-12_Review.csv',index_col=0)

In [275]:
data.head()

,name,titles,rating,comments
0,Yaswanth S.,An overall good premium experience,3.0,"SUMMERY: As a first time iPhone user, I would ..."
1,Navish Paik,Excellent product,4.0,Satisfied with the quality and performance but...
2,Mantu kumar,In the era of 14 this is still beast,4.0,"Using for few months, no heating issue, but ni..."
3,Yogesh Kumar Sharma,mujhe acha laga istmal kar ke,4.0,In 2022 best iPhone ever
4,Swapnil S Joshi,iphone 12 is good for normal use but don’t exp...,4.0,"Whereas brand is apple, you can expect standar..."

In [276]:
data.duplicated().sum()

14

In [277]:
data.drop_duplicates(inplace=True)

In [278]:
data.isna().sum()

name          0
titles        3
rating        0
comments    100
dtype: int64

In [279]:
data.dropna(inplace=True)

In [280]:
data.reset_index(inplace=True)

In [281]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     1920 non-null   int64
 1   name      1920 non-null   object
 2   titles    1920 non-null   object
 3   rating    1920 non-null   float64
 4   comments  1920 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 75.1+ KB

In [282]:
data.isna().sum()

index       0
name        0
titles      0
rating      0
comments    0
dtype: int64

In [283]:
data.duplicated().sum()

0

In [284]:
data1=data.loc[:,['comments']]

In [285]:
data1

                                               comments
0     SUMMERY: As a first time iPhone user, I would ...
1     Satisfied with the quality and performance but...
2     Using for few months, no heating issue, but ni...
3                              In 2022 best iPhone ever
4     Whereas brand is apple, you can expect standar...
...                                                 ...
1915      Upgraded from 7+. Amazing product. Loving it.
1916          No need to comment because this is Apple.
1917  Upgraded from iPhone x after over 3 years. I d...
1918  Just great, feel awesome to unbox all good at ...
1919                                   Good performance

[1920 rows x 1 columns]

In [286]:
# as you can there are still number there
import re

In [287]:
def remove_pattern(text,pattern):
    x=re.findall(pattern,str(text))
    for i in x:
        text=re.sub(i,'',str(text))
    return text

In [288]:
data1['cleaned']=data1['comments'].apply(lambda x: remove_pattern(x,'[0-9]*'))
data1

,comments,cleaned
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni..."
3,In 2022 best iPhone ever,In best iPhone ever
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar..."
...,...,...
1915,Upgraded from 7+. Amazing product. Loving it.,Upgraded from +. Amazing product. Loving it.
1916,No need to comment because this is Apple.,No need to comment because this is Apple.
1917,Upgraded from iPhone x after over 3 years. I d...,Upgraded from iPhone x after over years. I do...
1918,"Just great, feel awesome to unbox all good at ...","Just great, feel awesome to unbox all good at ..."
1919,Good performance,Good performance

In [289]:
from nltk.corpus import stopwords

In [290]:
# i didnt removed punctuations 
stop_words=list(stopwords.words('english'))

In [291]:
from nltk import word_tokenize

In [292]:
data1['tokenized']=[word_tokenize(x) for x in data1['cleaned']]
data1

,comments,cleaned,tokenized
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ...","[SUMMERY, :, As, a, first, time, iPhone, user,..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...,"[Satisfied, with, the, quality, and, performan..."
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni...","[Using, for, few, months, ,, no, heating, issu..."
3,In 2022 best iPhone ever,In best iPhone ever,"[In, best, iPhone, ever]"
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar...","[Whereas, brand, is, apple, ,, you, can, expec..."
...,...,...,...
1915,Upgraded from 7+. Amazing product. Loving it.,Upgraded from +. Amazing product. Loving it.,"[Upgraded, from, +, ., Amazing, product, ., Lo..."
1916,No need to comment because this is Apple.,No need to comment because this is Apple.,"[No, need, to, comment, because, this, is, App..."
1917,Upgraded from iPhone x after over 3 years. I d...,Upgraded from iPhone x after over years. I do...,"[Upgraded, from, iPhone, x, after, over, years..."
1918,"Just great, feel awesome to unbox all good at ...","Just great, feel awesome to unbox all good at ...","[Just, great, ,, feel, awesome, to, unbox, all..."
1919,Good performance,Good performance,"[Good, performance]"

In [293]:
data1['tokenized']=data1['tokenized'].apply(lambda x: [word for word in x if word not in stop_words])

In [294]:
data1.head()

,comments,cleaned,tokenized
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ...","[SUMMERY, :, As, first, time, iPhone, user, ,,..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...,"[Satisfied, quality, performance, 's, battery,..."
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni...","[Using, months, ,, heating, issue, ,, night, c..."
3,In 2022 best iPhone ever,In best iPhone ever,"[In, best, iPhone, ever]"
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar...","[Whereas, brand, apple, ,, expect, standard, h..."

In [295]:
data1

,comments,cleaned,tokenized
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ...","[SUMMERY, :, As, first, time, iPhone, user, ,,..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...,"[Satisfied, quality, performance, 's, battery,..."
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni...","[Using, months, ,, heating, issue, ,, night, c..."
3,In 2022 best iPhone ever,In best iPhone ever,"[In, best, iPhone, ever]"
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar...","[Whereas, brand, apple, ,, expect, standard, h..."
...,...,...,...
1915,Upgraded from 7+. Amazing product. Loving it.,Upgraded from +. Amazing product. Loving it.,"[Upgraded, +, ., Amazing, product, ., Loving, .]"
1916,No need to comment because this is Apple.,No need to comment because this is Apple.,"[No, need, comment, Apple, .]"
1917,Upgraded from iPhone x after over 3 years. I d...,Upgraded from iPhone x after over years. I do...,"[Upgraded, iPhone, x, years, ., I, ’, see, maj..."
1918,"Just great, feel awesome to unbox all good at ...","Just great, feel awesome to unbox all good at ...","[Just, great, ,, feel, awesome, unbox, good, f..."
1919,Good performance,Good performance,"[Good, performance]"

In [296]:
from nltk import PorterStemmer

In [297]:
stemm=PorterStemmer()

In [298]:
data1['tokenized']=data1['tokenized'].apply(lambda x:[stemm.stem(i) for i in x])

In [299]:
data1.head()

,comments,cleaned,tokenized
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ...","[summeri, :, as, first, time, iphon, user, ,, ..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...,"[satisfi, qualiti, perform, 's, batteri, drain..."
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni...","[use, month, ,, heat, issu, ,, night, camera, ..."
3,In 2022 best iPhone ever,In best iPhone ever,"[in, best, iphon, ever]"
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar...","[wherea, brand, appl, ,, expect, standard, han..."

In [300]:
data1['tokenized']=data1['tokenized'].apply(lambda x:' '.join(x))

In [301]:
data1

,comments,cleaned,tokenized
0,"SUMMERY: As a first time iPhone user, I would ...","SUMMERY: As a first time iPhone user, I would ...","summeri : as first time iphon user , i would s..."
1,Satisfied with the quality and performance but...,Satisfied with the quality and performance but...,satisfi qualiti perform 's batteri drain quick...
2,"Using for few months, no heating issue, but ni...","Using for few months, no heating issue, but ni...","use month , heat issu , night camera worst ."
3,In 2022 best iPhone ever,In best iPhone ever,in best iphon ever
4,"Whereas brand is apple, you can expect standar...","Whereas brand is apple, you can expect standar...","wherea brand appl , expect standard handset . ..."
...,...,...,...
1915,Upgraded from 7+. Amazing product. Loving it.,Upgraded from +. Amazing product. Loving it.,upgrad + . amaz product . love .
1916,No need to comment because this is Apple.,No need to comment because this is Apple.,no need comment appl .
1917,Upgraded from iPhone x after over 3 years. I d...,Upgraded from iPhone x after over years. I do...,upgrad iphon x year . i ’ see major chang upgr...
1918,"Just great, feel awesome to unbox all good at ...","Just great, feel awesome to unbox all good at ...","just great , feel awesom unbox good first conf..."
1919,Good performance,Good performance,good perform

In [302]:
data2=data1.loc[:,['tokenized']]

In [303]:
data2

                                              tokenized
0     summeri : as first time iphon user , i would s...
1     satisfi qualiti perform 's batteri drain quick...
2          use month , heat issu , night camera worst .
3                                    in best iphon ever
4     wherea brand appl , expect standard handset . ...
...                                                 ...
1915                   upgrad + . amaz product . love .
1916                             no need comment appl .
1917  upgrad iphon x year . i ’ see major chang upgr...
1918  just great , feel awesom unbox good first conf...
1919                                       good perform

[1920 rows x 1 columns]

In [304]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [305]:
analyser=SentimentIntensityAnalyzer()

In [306]:
def sentiment_score(text):
    analyser=SentimentIntensityAnalyzer()
    senti_dict=analyser.polarity_scores(text)
    senti=[]
    for i in senti_dict:
        if senti_dict['compound']>0.5:
            senti.append(1)
        elif senti_dict['compound']<=-0.5:
            senti.append(2)
        else :
            senti.append(0)
    
    return senti[0]

In [307]:
data3=data2

In [308]:
data3

                                              tokenized
0     summeri : as first time iphon user , i would s...
1     satisfi qualiti perform 's batteri drain quick...
2          use month , heat issu , night camera worst .
3                                    in best iphon ever
4     wherea brand appl , expect standard handset . ...
...                                                 ...
1915                   upgrad + . amaz product . love .
1916                             no need comment appl .
1917  upgrad iphon x year . i ’ see major chang upgr...
1918  just great , feel awesom unbox good first conf...
1919                                       good perform

[1920 rows x 1 columns]

In [309]:
data3['target']=data3['tokenized'].apply(lambda x: sentiment_score(x))

In [310]:
data3

                                              tokenized  target
0     summeri : as first time iphon user , i would s...       1
1     satisfi qualiti perform 's batteri drain quick...       0
2          use month , heat issu , night camera worst .       2
3                                    in best iphon ever       1
4     wherea brand appl , expect standard handset . ...       1
...                                                 ...     ...
1915                   upgrad + . amaz product . love .       1
1916                             no need comment appl .       0
1917  upgrad iphon x year . i ’ see major chang upgr...       1
1918  just great , feel awesom unbox good first conf...       1
1919                                       good perform       0

[1920 rows x 2 columns]

In [311]:
data3[data3['target']==2]

                                              tokenized  target
2          use month , heat issu , night camera worst .       2
209   hello , i write review - day usag , iphon beas...       2
239   if u cn compromis wit batri den go fr .. el dn...       2
263   the media could load . deliveri amazon amaz . ...       2
275   i ’ write review later , short , hardcor andro...       2
...                                                 ...     ...
1831  in descript iphon . inch display , actual rece...       2
1834  worst ever phone low camera batteri life low q...       2
1839  wast money display qualiti also poor batteri w...       2
1876                         i amma die hard iphon user       2
1888  i disappoint see charger earphon . it ’ sad ap...       2

[79 rows x 2 columns]

In [312]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tokenized  1920 non-null   object
 1   target     1920 non-null   int64
dtypes: int64(1), object(1)
memory usage: 30.1+ KB

In [313]:
data3['target'].value_counts()

0    1064
1     777
2      79
Name: target, dtype: int64

###  now we using CountVector

In [314]:
from sklearn.feature_extraction.text import CountVectorizer

In [315]:
cv=CountVectorizer()
cv_text=cv.fit_transform(data3['tokenized'])

### Logistic Regression

In [316]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

In [317]:
lr=LogisticRegression()
sm=SMOTE()

In [318]:
x=cv_text
y=data3['target']

In [319]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)

In [320]:
x_train,y_train=sm.fit_resample(x_train,y_train)

In [321]:
y_train.value_counts()

1    713
0    713
2    713
Name: target, dtype: int64

In [322]:
model_log=lr.fit(x_train,y_train)

In [323]:
print('accuracy :',model_log.score(x_train,y_train)*100)

accuracy : 95.41841982234689

In [324]:
print('accuracy :',model_log.score(x_test,y_test)*100)

accuracy : 74.13249211356468

In [325]:
y_pred=model_log.predict(x_test)

In [326]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.75      0.79      0.77       331
           1       0.76      0.86      0.80       228
           2       0.50      0.16      0.24        75

    accuracy                           0.74       634
   macro avg       0.67      0.60      0.61       634
weighted avg       0.72      0.74      0.72       634

### Naive Bayes

In [327]:
from sklearn.naive_bayes import MultinomialNB

In [328]:
nb=MultinomialNB()
model_2=nb.fit(x_train,y_train)

In [329]:
print('accuracy :',model_2.score(x_train,y_train)*100)

accuracy : 77.27910238429172

In [330]:
print('accuracy :',model_2.score(x_test,y_test)*100)

accuracy : 63.24921135646687

In [331]:
y_pred=model_2.predict(x_test)

In [332]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.48      0.81      0.60       208
           1       0.87      0.58      0.70       388
           2       0.33      0.21      0.26        38

    accuracy                           0.63       634
   macro avg       0.56      0.53      0.52       634
weighted avg       0.71      0.63      0.64       634

### Decision Tree

In [333]:
from sklearn.tree import DecisionTreeClassifier

In [334]:
dt=DecisionTreeClassifier()
model_3=dt.fit(x_train,y_train)

In [335]:
print('accuracy :',model_3.score(x_train,y_train)*100)

accuracy : 97.84946236559139

In [336]:
print('accuracy :',model_3.score(x_test,y_test)*100)

accuracy : 76.65615141955836

In [337]:
y_pred=model_3.predict(x_test)

In [338]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.77      0.84      0.80       321
           1       0.79      0.82      0.80       248
           2       0.54      0.20      0.29        65

    accuracy                           0.77       634
   macro avg       0.70      0.62      0.63       634
weighted avg       0.75      0.77      0.75       634

### Now we are using TF-IDF

In [339]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [340]:
tf=TfidfVectorizer()
tf_text=tf.fit_transform(data3['tokenized'])

In [341]:
x=tf_text
y=data3['target']

In [342]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)
x_train,y_train=sm.fit_resample(x_train,y_train)
y_train.value_counts()

1    713
0    713
2    713
Name: target, dtype: int64

### Logistic regression

In [343]:
lr=LogisticRegression()
tf_model_1=lr.fit(x_train,y_train)

In [344]:
print('accuracy :',tf_model_1.score(x_train,y_train)*100)

accuracy : 94.109396914446

In [345]:
print('accuracy :',tf_model_1.score(x_test,y_test)*100)

accuracy : 80.12618296529969

In [346]:
y_pred=tf_model_1.predict(x_test)

In [347]:
print(classification_report(y_pred,y_test)) #80

              precision    recall  f1-score   support

           0       0.86      0.81      0.83       375
           1       0.75      0.81      0.78       241
           2       0.46      0.61      0.52        18

    accuracy                           0.80       634
   macro avg       0.69      0.74      0.71       634
weighted avg       0.81      0.80      0.80       634

###  Naive bayes

In [348]:
tf_model_2=nb.fit(x_train,y_train)

In [349]:
print('accuracy :',tf_model_2.score(x_train,y_train)*100)

accuracy : 88.12529219261337

In [350]:
print('accuracy :',tf_model_2.score(x_test,y_test)*100)

accuracy : 65.14195583596214

In [351]:
y_pred=tf_model_2.predict(x_test)

In [352]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.52      0.85      0.65       215
           1       0.83      0.65      0.73       333
           2       0.62      0.17      0.27        86

    accuracy                           0.65       634
   macro avg       0.66      0.56      0.55       634
weighted avg       0.70      0.65      0.64       634

### Decision Tree

In [353]:
dt=DecisionTreeClassifier()
tf_model_3=dt.fit(x_train,y_train)
print('accuracy :',tf_model_3.score(x_train,y_train)*100)

accuracy : 99.62599345488546

In [354]:
print('accuracy :',tf_model_3.score(x_test,y_test)*100)

accuracy : 79.33753943217665

In [355]:
y_pred=tf_model_3.predict(x_test)

In [356]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.86      0.80      0.83       377
           1       0.73      0.82      0.77       228
           2       0.54      0.45      0.49        29

    accuracy                           0.79       634
   macro avg       0.71      0.69      0.70       634
weighted avg       0.80      0.79      0.79       634

### as we can see in TF-IDF if we use Logistic Rgeression we got 80% accuracy in test data so if i use other algorithms. then may get better model with better accuracy compare to Logistic Regression